#########################################
#########################################

## RPECK 31/10/2022 - Statamic Push    ##

#########################################
#########################################

## Name ##
name: Push Statamic To Production Server

## Triggers ##
on:
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# Jobs
jobs:

  # Push
  push:
  
    # Name
    name: Push with SCP
  
    # OS
    runs-on: ubuntu-latest
    
    # Steps
    steps:
    
      # Checkout Repo
      - uses: actions/checkout@v3
      
      # Upload SCP
      - name: Copy Files Via SCP
        uses: appleboy/scp-action@master
        with:
          host:             ${{ secrets.HOST }}
          username:         ${{ secrets.USERNAME }}
          port:             ${{ secrets.PORT }}
          key:              ${{ secrets.KEY }}
          passphrase:       ${{ secrets.PASSPHRASE }}
          target:           ${{ secrets.TARGET }}
          source:           ${{ github.workspace }}
          overwrite:        true
          strip_components: 2
          
      # Reload NGinx
      - name: Reload NGinx
        uses: appleboy/ssh-action@master
        with:
          host:       ${{ secrets.HOST }}
          username:   ${{ secrets.USERNAME }}
          port:       ${{ secrets.PORT }}
          key:        ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ${{ secrets.TARGET }}
            sudo chown -R ${{ secrets.USERNAME }}:www-data .
            sudo find . -type f -exec chmod 664 {} \;   
            sudo find . -type d -exec chmod 775 {} \;
            sudo find . -type d -exec chmod g+s {} \;
            sudo chgrp -R www-data storage bootstrap/cache 
            sudo chmod -R ug+rwx storage bootstrap/cache
            composer update
            php artisan cache:clear
            composer dump-autoload
            sudo service nginx reload
